SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS attendance;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS leave_applications;
DROP TABLE IF EXISTS schedules;
DROP TABLE IF EXISTS substitutions;
DROP TABLE IF EXISTS classrooms;
DROP TABLE IF EXISTS users;
SET FOREIGN_KEY_CHECKS = 1;
